version: "3.8"

services:
  bb_backend:
    image: nvidia/cuda:10.2-cudnn7-devel
    container_name: bb_backend
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./bb_platform/.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - FORCE_CUDA=1
      - PATH=/root/.local/bin:${PATH}
    command: [sh, -c, " sleep infinity"]              # for configuration
    # command: [sh, -c, " apt-get update && apt-get install -y python3-opencv ca-certificates python3-dev python3-pip git wget sudo cmake ninja-build && rm -rf /var/lib/apt/lists/* && ln -sv /usr/bin/python3 /usr/bin/python && ln -sv /usr/bin/pip3 /usr/bin/pip && pip install --user -r requirements.txt --no-cache-dir && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"] # for initial run
    # command: [sh, -c, "gunicorn bb_platform.wsgi --bind 0.0.0.0:8080"] # for rutines run
    # command: [sh, -c, " ln -sv /usr/bin/python3 /usr/bin/python && ln -sv /usr/bin/pip3 /usr/bin/pip && gunicorn bb_platform.wsgi --bind 0.0.0.0:8080"] # for initial run

    ports:
      - "8000:8000"